### PR TITLE
Add iac US to codeowners

### PR DESCRIPTION
**Pull request by yorinasub17**
Adding all the IAC team US to codeowners.

### CODE REVIEW

**Review by bwhaley — COMMENTED** [review]
Should the entire team be CODEOWNERS? Or a subset? Trying to avoid overloading the team with too many repos to watch.

**Comment by yorinasub17** [comment]
Well right now the people listed here are, or have a desire to be, experts in EKS, so it makes sense. I think we should keep it at this size though.

**Review by bwhaley — APPROVED** [review]
Sounds good.

**Comment by yorinasub17** [comment]
Thanks for review! Will merge in now.

**Pull request merged**
