### PR TITLE
Release v0.1.5

### PR DESCRIPTION
**Pull request by yorinasub17**

### CODE REVIEW

**Review by zackproser — APPROVED** [review]

**Comment by yorinasub17** [comment]
Thanks Zack!

**Comment by rhoboat** [comment]
I don't get it... how does this change release a new version? It's a change to a yaml file. 🤔

**Comment by yorinasub17** [comment]
So this is the way you host helm repositories in github pages. A helm repo is a web accessible page that serves a `index.yaml` file that it uses to get the metadata on which chart versions are available and hosted.

So here, we are using github pages to provide a website that publishes our `index.yaml` files, which point to the respective chart tarball hosted at https://github.com/gruntwork-io/helm-kubernetes-services/releases. You can see this in action if you go to helmcharts.gruntwork.io/index.yaml and note how it serves this yaml file.

**Comment by rhoboat** [comment]
Interesting! Thank you for explaining!

**Pull request merged**
